package com.cn.model;

import java.math.BigDecimal;

public class Commodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.brief
     *
     * @mbggenerated
     */
    private String brief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_commodity
     *
     * @mbggenerated
     */
    public Commodity(String id, String name, BigDecimal price, String brief, String status, Integer seq, String remark) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.brief = brief;
        this.status = status;
        this.seq = seq;
        this.remark = remark;
    }

    public Commodity() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.id
     *
     * @return the value of t_commodity.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.name
     *
     * @return the value of t_commodity.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.price
     *
     * @return the value of t_commodity.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.brief
     *
     * @return the value of t_commodity.brief
     *
     * @mbggenerated
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.status
     *
     * @return the value of t_commodity.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.seq
     *
     * @return the value of t_commodity.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.remark
     *
     * @return the value of t_commodity.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public void setBrief(String brief) {
        this.brief = brief;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}