package com.cn.model;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.display_name
     *
     * @mbggenerated
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.birthdate
     *
     * @mbggenerated
     */
    private Date birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.badge
     *
     * @mbggenerated
     */
    private String badge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.gender
     *
     * @mbggenerated
     */
    private String gender;

    public Customer() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated
     */

    public Customer(String id, String type, String loginName, String displayName, String password, Date birthdate, String status, String badge, String address, String remark, Date createTime, String gender) {
        this.id = id;
        this.type = type;
        this.loginName = loginName;
        this.displayName = displayName;
        this.password = password;
        this.birthdate = birthdate;
        this.status = status;
        this.badge = badge;
        this.address = address;
        this.remark = remark;
        this.createTime = createTime;
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.Id
     *
     * @return the value of t_customer.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.type
     *
     * @return the value of t_customer.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.login_name
     *
     * @return the value of t_customer.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.display_name
     *
     * @return the value of t_customer.display_name
     *
     * @mbggenerated
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.password
     *
     * @return the value of t_customer.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.birthdate
     *
     * @return the value of t_customer.birthdate
     *
     * @mbggenerated
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.status
     *
     * @return the value of t_customer.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.badge
     *
     * @return the value of t_customer.badge
     *
     * @mbggenerated
     */
    public String getBadge() {
        return badge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.address
     *
     * @return the value of t_customer.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.remark
     *
     * @return the value of t_customer.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.create_time
     *
     * @return the value of t_customer.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.gender
     *
     * @return the value of t_customer.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setBadge(String badge) {
        this.badge = badge;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }
}